#!/usr/bin/env bash
psql "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB?sslmode=disable" <<-EOSQL
create table activity
(
    partition_name varchar(255) not null,
    thread_name    varchar(255) not null,
    username       varchar(255) not null,
    primary key (partition_name, thread_name, username)
);

alter table activity
    owner to postgres;

create table forum_user
(
    username   varchar(255) not null
        primary key,
    created_at timestamp,
    passwd     varchar(255),
    status     varchar(255),
    userrole   varchar(255)
);

alter table forum_user
    owner to postgres;

create table forum_partition
(
    partition_name varchar(255) not null
        primary key,
    created_at     timestamp,
    general_access boolean,
    created_by     varchar(255)
        constraint fkm3t2mbcvy7l84m210pyijlb5u
            references forum_user
);

alter table forum_partition
    owner to postgres;

create table thread
(
    partition_name varchar(255) not null
        constraint fk8ub05sw1c3c6rhe9bm2u5ro3u
            references forum_partition,
    thread_name    varchar(255) not null,
    created_at     timestamp,
    created_by     varchar(255)
        constraint fk2fxiu3s4wkplgfkbawffdu8nb
            references forum_user,
    primary key (partition_name, thread_name)
);

alter table thread
    owner to postgres;

create table forum_message
(
    message_id     bigint generated by default as identity
        primary key,
    created_at     timestamp,
    message_txt    varchar(255),
    username       varchar(255)
        constraint fkiwyhjq6xvqjh5mo7wenbgry3w
            references forum_user,
    reply_to       bigint
        constraint fk1xdduuoukmo04ok6ft4doaesu
            references forum_message,
    partition_name varchar(255),
    thread_name    varchar(255),
    constraint fkkv1mb3nbcye1methwogox0pq3
        foreign key (partition_name, thread_name) references thread
);

alter table forum_message
    owner to postgres;

INSERT INTO forum_user (username, passwd, status, userrole) VALUES
        ('123', '123', '123', 'MODERATOR'),
        ('Doom Slayer', 'iddqd', 'rip and tear', 'MODERATOR'),
        ('The Dark Lord', 'idkfa', 'ripped and teared', 'MODERATOR'),
        ('Khan Maykr', 'orb', 'dead', 'BANNED'),
        ('Imp', '666', '*angry noises*', 'COMMON'),
        ('Cacodemon', '666', '*meatball noises*', 'COMMON'),
        ('Mancubus', '666', '*fat noises*', 'BANNED'),
        ('Cyberdemon', '666', 'horny', 'BANNED');

INSERT INTO forum_partition (partition_name, created_by, general_access) VALUES
        ('Earth', 'The Dark Lord', true),
        ('Hell', 'The Dark Lord', true),
        ('Mars', 'The Dark Lord', true),
        ('Fortress of Doom', 'Khan Maykr', false);

INSERT INTO thread (partition_name, thread_name, created_by) VALUES
        ('Earth', 'Hell on Earth', 'Khan Maykr'),
        ('Earth', 'Exultia', 'The Dark Lord'),
        ('Earth', 'Super Gore Nest', 'Khan Maykr'),
        ('Hell', 'Nekravol', 'The Dark Lord'),
        ('Mars', 'E1M1', '123'),
        ('Mars', 'E1M5', '123'),
        ('Mars', 'E1M9', '123');

INSERT INTO forum_message(partition_name, thread_name, username, message_txt) VALUES
        ('Earth', 'Hell on Earth', 'Khan Maykr', 'You get it?) Hell, Earth and then... Hell on Earth)) Is it funny?)'),
        ('Earth', 'Hell on Earth', 'Doom Slayer', 'Not really.'),
        ('Earth', 'Exultia', '123', 'What is this word even suppose to mean?'),
        ('Earth', 'Exultia', 'The Dark Lord', 'Your puny mind can not comprehend it'),
        ('Earth', 'Exultia', '123', 'Yeah yeah nvm'),
        ('Earth', 'Super Gore Nest', 'Cacodemon', 'Is anyone alive?'),
        ('Earth', 'Super Gore Nest', 'Doom Slayer', 'Not really.'),
        ('Hell', 'Nekravol', '123', 'Same question..'),
        ('Mars', 'E1M1', 'Imp', 'Good times)'),
        ('Mars', 'E1M1', 'Doom Slayer', 'Not really.');

INSERT INTO activity(partition_name, thread_name, username) VALUES
        ('Earth', 'Hell on Earth', 'Khan Maykr'),
        ('Earth', 'Hell on Earth', 'Doom Slayer'),
        ('Earth', 'Exultia', '123'),
        ('Earth', 'Exultia', 'The Dark Lord'),
        ('Earth', 'Super Gore Nest', 'Cacodemon'),
        ('Earth', 'Super Gore Nest', 'Doom Slayer'),
        ('Hell', 'Nekravol', '123'),
        ('Mars', 'E1M1', 'Imp'),
        ('Mars', 'E1M1', 'Doom Slayer');
EOSQL